// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: constraint_solver/assignment.proto

#ifndef PROTOBUF_constraint_5fsolver_2fassignment_2eproto__INCLUDED
#define PROTOBUF_constraint_5fsolver_2fassignment_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace operations_research {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_constraint_5fsolver_2fassignment_2eproto();
void protobuf_AssignDesc_constraint_5fsolver_2fassignment_2eproto();
void protobuf_ShutdownFile_constraint_5fsolver_2fassignment_2eproto();

class AssignmentProto;
class IntVarAssignment;
class IntervalVarAssignment;
class SequenceVarAssignment;
class WorkerInfo;

// ===================================================================

class IntVarAssignment : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:operations_research.IntVarAssignment) */ {
 public:
  IntVarAssignment();
  virtual ~IntVarAssignment();

  IntVarAssignment(const IntVarAssignment& from);

  inline IntVarAssignment& operator=(const IntVarAssignment& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const IntVarAssignment& default_instance();

  void Swap(IntVarAssignment* other);

  // implements Message ----------------------------------------------

  inline IntVarAssignment* New() const { return New(NULL); }

  IntVarAssignment* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const IntVarAssignment& from);
  void MergeFrom(const IntVarAssignment& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(IntVarAssignment* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string var_id = 1;
  void clear_var_id();
  static const int kVarIdFieldNumber = 1;
  const ::std::string& var_id() const;
  void set_var_id(const ::std::string& value);
  void set_var_id(const char* value);
  void set_var_id(const char* value, size_t size);
  ::std::string* mutable_var_id();
  ::std::string* release_var_id();
  void set_allocated_var_id(::std::string* var_id);

  // optional int64 min = 2;
  void clear_min();
  static const int kMinFieldNumber = 2;
  ::google::protobuf::int64 min() const;
  void set_min(::google::protobuf::int64 value);

  // optional int64 max = 3;
  void clear_max();
  static const int kMaxFieldNumber = 3;
  ::google::protobuf::int64 max() const;
  void set_max(::google::protobuf::int64 value);

  // optional bool active = 4;
  void clear_active();
  static const int kActiveFieldNumber = 4;
  bool active() const;
  void set_active(bool value);

  // @@protoc_insertion_point(class_scope:operations_research.IntVarAssignment)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr var_id_;
  ::google::protobuf::int64 min_;
  ::google::protobuf::int64 max_;
  bool active_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_constraint_5fsolver_2fassignment_2eproto();
  friend void protobuf_AssignDesc_constraint_5fsolver_2fassignment_2eproto();
  friend void protobuf_ShutdownFile_constraint_5fsolver_2fassignment_2eproto();

  void InitAsDefaultInstance();
  static IntVarAssignment* default_instance_;
};
// -------------------------------------------------------------------

class IntervalVarAssignment : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:operations_research.IntervalVarAssignment) */ {
 public:
  IntervalVarAssignment();
  virtual ~IntervalVarAssignment();

  IntervalVarAssignment(const IntervalVarAssignment& from);

  inline IntervalVarAssignment& operator=(const IntervalVarAssignment& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const IntervalVarAssignment& default_instance();

  void Swap(IntervalVarAssignment* other);

  // implements Message ----------------------------------------------

  inline IntervalVarAssignment* New() const { return New(NULL); }

  IntervalVarAssignment* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const IntervalVarAssignment& from);
  void MergeFrom(const IntervalVarAssignment& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(IntervalVarAssignment* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string var_id = 1;
  void clear_var_id();
  static const int kVarIdFieldNumber = 1;
  const ::std::string& var_id() const;
  void set_var_id(const ::std::string& value);
  void set_var_id(const char* value);
  void set_var_id(const char* value, size_t size);
  ::std::string* mutable_var_id();
  ::std::string* release_var_id();
  void set_allocated_var_id(::std::string* var_id);

  // optional int64 start_min = 2;
  void clear_start_min();
  static const int kStartMinFieldNumber = 2;
  ::google::protobuf::int64 start_min() const;
  void set_start_min(::google::protobuf::int64 value);

  // optional int64 start_max = 3;
  void clear_start_max();
  static const int kStartMaxFieldNumber = 3;
  ::google::protobuf::int64 start_max() const;
  void set_start_max(::google::protobuf::int64 value);

  // optional int64 duration_min = 4;
  void clear_duration_min();
  static const int kDurationMinFieldNumber = 4;
  ::google::protobuf::int64 duration_min() const;
  void set_duration_min(::google::protobuf::int64 value);

  // optional int64 duration_max = 5;
  void clear_duration_max();
  static const int kDurationMaxFieldNumber = 5;
  ::google::protobuf::int64 duration_max() const;
  void set_duration_max(::google::protobuf::int64 value);

  // optional int64 end_min = 6;
  void clear_end_min();
  static const int kEndMinFieldNumber = 6;
  ::google::protobuf::int64 end_min() const;
  void set_end_min(::google::protobuf::int64 value);

  // optional int64 end_max = 7;
  void clear_end_max();
  static const int kEndMaxFieldNumber = 7;
  ::google::protobuf::int64 end_max() const;
  void set_end_max(::google::protobuf::int64 value);

  // optional int64 performed_min = 8;
  void clear_performed_min();
  static const int kPerformedMinFieldNumber = 8;
  ::google::protobuf::int64 performed_min() const;
  void set_performed_min(::google::protobuf::int64 value);

  // optional int64 performed_max = 9;
  void clear_performed_max();
  static const int kPerformedMaxFieldNumber = 9;
  ::google::protobuf::int64 performed_max() const;
  void set_performed_max(::google::protobuf::int64 value);

  // optional bool active = 10;
  void clear_active();
  static const int kActiveFieldNumber = 10;
  bool active() const;
  void set_active(bool value);

  // @@protoc_insertion_point(class_scope:operations_research.IntervalVarAssignment)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr var_id_;
  ::google::protobuf::int64 start_min_;
  ::google::protobuf::int64 start_max_;
  ::google::protobuf::int64 duration_min_;
  ::google::protobuf::int64 duration_max_;
  ::google::protobuf::int64 end_min_;
  ::google::protobuf::int64 end_max_;
  ::google::protobuf::int64 performed_min_;
  ::google::protobuf::int64 performed_max_;
  bool active_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_constraint_5fsolver_2fassignment_2eproto();
  friend void protobuf_AssignDesc_constraint_5fsolver_2fassignment_2eproto();
  friend void protobuf_ShutdownFile_constraint_5fsolver_2fassignment_2eproto();

  void InitAsDefaultInstance();
  static IntervalVarAssignment* default_instance_;
};
// -------------------------------------------------------------------

class SequenceVarAssignment : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:operations_research.SequenceVarAssignment) */ {
 public:
  SequenceVarAssignment();
  virtual ~SequenceVarAssignment();

  SequenceVarAssignment(const SequenceVarAssignment& from);

  inline SequenceVarAssignment& operator=(const SequenceVarAssignment& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SequenceVarAssignment& default_instance();

  void Swap(SequenceVarAssignment* other);

  // implements Message ----------------------------------------------

  inline SequenceVarAssignment* New() const { return New(NULL); }

  SequenceVarAssignment* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SequenceVarAssignment& from);
  void MergeFrom(const SequenceVarAssignment& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SequenceVarAssignment* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string var_id = 1;
  void clear_var_id();
  static const int kVarIdFieldNumber = 1;
  const ::std::string& var_id() const;
  void set_var_id(const ::std::string& value);
  void set_var_id(const char* value);
  void set_var_id(const char* value, size_t size);
  ::std::string* mutable_var_id();
  ::std::string* release_var_id();
  void set_allocated_var_id(::std::string* var_id);

  // repeated int32 forward_sequence = 2;
  int forward_sequence_size() const;
  void clear_forward_sequence();
  static const int kForwardSequenceFieldNumber = 2;
  ::google::protobuf::int32 forward_sequence(int index) const;
  void set_forward_sequence(int index, ::google::protobuf::int32 value);
  void add_forward_sequence(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      forward_sequence() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_forward_sequence();

  // repeated int32 backward_sequence = 3;
  int backward_sequence_size() const;
  void clear_backward_sequence();
  static const int kBackwardSequenceFieldNumber = 3;
  ::google::protobuf::int32 backward_sequence(int index) const;
  void set_backward_sequence(int index, ::google::protobuf::int32 value);
  void add_backward_sequence(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      backward_sequence() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_backward_sequence();

  // repeated int32 unperformed = 4;
  int unperformed_size() const;
  void clear_unperformed();
  static const int kUnperformedFieldNumber = 4;
  ::google::protobuf::int32 unperformed(int index) const;
  void set_unperformed(int index, ::google::protobuf::int32 value);
  void add_unperformed(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      unperformed() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_unperformed();

  // optional bool active = 5;
  void clear_active();
  static const int kActiveFieldNumber = 5;
  bool active() const;
  void set_active(bool value);

  // @@protoc_insertion_point(class_scope:operations_research.SequenceVarAssignment)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr var_id_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > forward_sequence_;
  mutable int _forward_sequence_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > backward_sequence_;
  mutable int _backward_sequence_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > unperformed_;
  mutable int _unperformed_cached_byte_size_;
  bool active_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_constraint_5fsolver_2fassignment_2eproto();
  friend void protobuf_AssignDesc_constraint_5fsolver_2fassignment_2eproto();
  friend void protobuf_ShutdownFile_constraint_5fsolver_2fassignment_2eproto();

  void InitAsDefaultInstance();
  static SequenceVarAssignment* default_instance_;
};
// -------------------------------------------------------------------

class WorkerInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:operations_research.WorkerInfo) */ {
 public:
  WorkerInfo();
  virtual ~WorkerInfo();

  WorkerInfo(const WorkerInfo& from);

  inline WorkerInfo& operator=(const WorkerInfo& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WorkerInfo& default_instance();

  void Swap(WorkerInfo* other);

  // implements Message ----------------------------------------------

  inline WorkerInfo* New() const { return New(NULL); }

  WorkerInfo* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const WorkerInfo& from);
  void MergeFrom(const WorkerInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(WorkerInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 worker_id = 1;
  void clear_worker_id();
  static const int kWorkerIdFieldNumber = 1;
  ::google::protobuf::int32 worker_id() const;
  void set_worker_id(::google::protobuf::int32 value);

  // optional string bns = 2;
  void clear_bns();
  static const int kBnsFieldNumber = 2;
  const ::std::string& bns() const;
  void set_bns(const ::std::string& value);
  void set_bns(const char* value);
  void set_bns(const char* value, size_t size);
  ::std::string* mutable_bns();
  ::std::string* release_bns();
  void set_allocated_bns(::std::string* bns);

  // @@protoc_insertion_point(class_scope:operations_research.WorkerInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr bns_;
  ::google::protobuf::int32 worker_id_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_constraint_5fsolver_2fassignment_2eproto();
  friend void protobuf_AssignDesc_constraint_5fsolver_2fassignment_2eproto();
  friend void protobuf_ShutdownFile_constraint_5fsolver_2fassignment_2eproto();

  void InitAsDefaultInstance();
  static WorkerInfo* default_instance_;
};
// -------------------------------------------------------------------

class AssignmentProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:operations_research.AssignmentProto) */ {
 public:
  AssignmentProto();
  virtual ~AssignmentProto();

  AssignmentProto(const AssignmentProto& from);

  inline AssignmentProto& operator=(const AssignmentProto& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AssignmentProto& default_instance();

  void Swap(AssignmentProto* other);

  // implements Message ----------------------------------------------

  inline AssignmentProto* New() const { return New(NULL); }

  AssignmentProto* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AssignmentProto& from);
  void MergeFrom(const AssignmentProto& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(AssignmentProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .operations_research.IntVarAssignment int_var_assignment = 1;
  int int_var_assignment_size() const;
  void clear_int_var_assignment();
  static const int kIntVarAssignmentFieldNumber = 1;
  const ::operations_research::IntVarAssignment& int_var_assignment(int index) const;
  ::operations_research::IntVarAssignment* mutable_int_var_assignment(int index);
  ::operations_research::IntVarAssignment* add_int_var_assignment();
  ::google::protobuf::RepeatedPtrField< ::operations_research::IntVarAssignment >*
      mutable_int_var_assignment();
  const ::google::protobuf::RepeatedPtrField< ::operations_research::IntVarAssignment >&
      int_var_assignment() const;

  // repeated .operations_research.IntervalVarAssignment interval_var_assignment = 2;
  int interval_var_assignment_size() const;
  void clear_interval_var_assignment();
  static const int kIntervalVarAssignmentFieldNumber = 2;
  const ::operations_research::IntervalVarAssignment& interval_var_assignment(int index) const;
  ::operations_research::IntervalVarAssignment* mutable_interval_var_assignment(int index);
  ::operations_research::IntervalVarAssignment* add_interval_var_assignment();
  ::google::protobuf::RepeatedPtrField< ::operations_research::IntervalVarAssignment >*
      mutable_interval_var_assignment();
  const ::google::protobuf::RepeatedPtrField< ::operations_research::IntervalVarAssignment >&
      interval_var_assignment() const;

  // repeated .operations_research.SequenceVarAssignment sequence_var_assignment = 6;
  int sequence_var_assignment_size() const;
  void clear_sequence_var_assignment();
  static const int kSequenceVarAssignmentFieldNumber = 6;
  const ::operations_research::SequenceVarAssignment& sequence_var_assignment(int index) const;
  ::operations_research::SequenceVarAssignment* mutable_sequence_var_assignment(int index);
  ::operations_research::SequenceVarAssignment* add_sequence_var_assignment();
  ::google::protobuf::RepeatedPtrField< ::operations_research::SequenceVarAssignment >*
      mutable_sequence_var_assignment();
  const ::google::protobuf::RepeatedPtrField< ::operations_research::SequenceVarAssignment >&
      sequence_var_assignment() const;

  // optional .operations_research.IntVarAssignment objective = 3;
  bool has_objective() const;
  void clear_objective();
  static const int kObjectiveFieldNumber = 3;
  const ::operations_research::IntVarAssignment& objective() const;
  ::operations_research::IntVarAssignment* mutable_objective();
  ::operations_research::IntVarAssignment* release_objective();
  void set_allocated_objective(::operations_research::IntVarAssignment* objective);

  // optional .operations_research.WorkerInfo worker_info = 4;
  bool has_worker_info() const;
  void clear_worker_info();
  static const int kWorkerInfoFieldNumber = 4;
  const ::operations_research::WorkerInfo& worker_info() const;
  ::operations_research::WorkerInfo* mutable_worker_info();
  ::operations_research::WorkerInfo* release_worker_info();
  void set_allocated_worker_info(::operations_research::WorkerInfo* worker_info);

  // optional bool is_valid = 5;
  void clear_is_valid();
  static const int kIsValidFieldNumber = 5;
  bool is_valid() const;
  void set_is_valid(bool value);

  // @@protoc_insertion_point(class_scope:operations_research.AssignmentProto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::operations_research::IntVarAssignment > int_var_assignment_;
  ::google::protobuf::RepeatedPtrField< ::operations_research::IntervalVarAssignment > interval_var_assignment_;
  ::google::protobuf::RepeatedPtrField< ::operations_research::SequenceVarAssignment > sequence_var_assignment_;
  ::operations_research::IntVarAssignment* objective_;
  ::operations_research::WorkerInfo* worker_info_;
  bool is_valid_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_constraint_5fsolver_2fassignment_2eproto();
  friend void protobuf_AssignDesc_constraint_5fsolver_2fassignment_2eproto();
  friend void protobuf_ShutdownFile_constraint_5fsolver_2fassignment_2eproto();

  void InitAsDefaultInstance();
  static AssignmentProto* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// IntVarAssignment

// optional string var_id = 1;
inline void IntVarAssignment::clear_var_id() {
  var_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& IntVarAssignment::var_id() const {
  // @@protoc_insertion_point(field_get:operations_research.IntVarAssignment.var_id)
  return var_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void IntVarAssignment::set_var_id(const ::std::string& value) {
  
  var_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:operations_research.IntVarAssignment.var_id)
}
inline void IntVarAssignment::set_var_id(const char* value) {
  
  var_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:operations_research.IntVarAssignment.var_id)
}
inline void IntVarAssignment::set_var_id(const char* value, size_t size) {
  
  var_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:operations_research.IntVarAssignment.var_id)
}
inline ::std::string* IntVarAssignment::mutable_var_id() {
  
  // @@protoc_insertion_point(field_mutable:operations_research.IntVarAssignment.var_id)
  return var_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* IntVarAssignment::release_var_id() {
  // @@protoc_insertion_point(field_release:operations_research.IntVarAssignment.var_id)
  
  return var_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void IntVarAssignment::set_allocated_var_id(::std::string* var_id) {
  if (var_id != NULL) {
    
  } else {
    
  }
  var_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), var_id);
  // @@protoc_insertion_point(field_set_allocated:operations_research.IntVarAssignment.var_id)
}

// optional int64 min = 2;
inline void IntVarAssignment::clear_min() {
  min_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 IntVarAssignment::min() const {
  // @@protoc_insertion_point(field_get:operations_research.IntVarAssignment.min)
  return min_;
}
inline void IntVarAssignment::set_min(::google::protobuf::int64 value) {
  
  min_ = value;
  // @@protoc_insertion_point(field_set:operations_research.IntVarAssignment.min)
}

// optional int64 max = 3;
inline void IntVarAssignment::clear_max() {
  max_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 IntVarAssignment::max() const {
  // @@protoc_insertion_point(field_get:operations_research.IntVarAssignment.max)
  return max_;
}
inline void IntVarAssignment::set_max(::google::protobuf::int64 value) {
  
  max_ = value;
  // @@protoc_insertion_point(field_set:operations_research.IntVarAssignment.max)
}

// optional bool active = 4;
inline void IntVarAssignment::clear_active() {
  active_ = false;
}
inline bool IntVarAssignment::active() const {
  // @@protoc_insertion_point(field_get:operations_research.IntVarAssignment.active)
  return active_;
}
inline void IntVarAssignment::set_active(bool value) {
  
  active_ = value;
  // @@protoc_insertion_point(field_set:operations_research.IntVarAssignment.active)
}

// -------------------------------------------------------------------

// IntervalVarAssignment

// optional string var_id = 1;
inline void IntervalVarAssignment::clear_var_id() {
  var_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& IntervalVarAssignment::var_id() const {
  // @@protoc_insertion_point(field_get:operations_research.IntervalVarAssignment.var_id)
  return var_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void IntervalVarAssignment::set_var_id(const ::std::string& value) {
  
  var_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:operations_research.IntervalVarAssignment.var_id)
}
inline void IntervalVarAssignment::set_var_id(const char* value) {
  
  var_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:operations_research.IntervalVarAssignment.var_id)
}
inline void IntervalVarAssignment::set_var_id(const char* value, size_t size) {
  
  var_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:operations_research.IntervalVarAssignment.var_id)
}
inline ::std::string* IntervalVarAssignment::mutable_var_id() {
  
  // @@protoc_insertion_point(field_mutable:operations_research.IntervalVarAssignment.var_id)
  return var_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* IntervalVarAssignment::release_var_id() {
  // @@protoc_insertion_point(field_release:operations_research.IntervalVarAssignment.var_id)
  
  return var_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void IntervalVarAssignment::set_allocated_var_id(::std::string* var_id) {
  if (var_id != NULL) {
    
  } else {
    
  }
  var_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), var_id);
  // @@protoc_insertion_point(field_set_allocated:operations_research.IntervalVarAssignment.var_id)
}

// optional int64 start_min = 2;
inline void IntervalVarAssignment::clear_start_min() {
  start_min_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 IntervalVarAssignment::start_min() const {
  // @@protoc_insertion_point(field_get:operations_research.IntervalVarAssignment.start_min)
  return start_min_;
}
inline void IntervalVarAssignment::set_start_min(::google::protobuf::int64 value) {
  
  start_min_ = value;
  // @@protoc_insertion_point(field_set:operations_research.IntervalVarAssignment.start_min)
}

// optional int64 start_max = 3;
inline void IntervalVarAssignment::clear_start_max() {
  start_max_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 IntervalVarAssignment::start_max() const {
  // @@protoc_insertion_point(field_get:operations_research.IntervalVarAssignment.start_max)
  return start_max_;
}
inline void IntervalVarAssignment::set_start_max(::google::protobuf::int64 value) {
  
  start_max_ = value;
  // @@protoc_insertion_point(field_set:operations_research.IntervalVarAssignment.start_max)
}

// optional int64 duration_min = 4;
inline void IntervalVarAssignment::clear_duration_min() {
  duration_min_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 IntervalVarAssignment::duration_min() const {
  // @@protoc_insertion_point(field_get:operations_research.IntervalVarAssignment.duration_min)
  return duration_min_;
}
inline void IntervalVarAssignment::set_duration_min(::google::protobuf::int64 value) {
  
  duration_min_ = value;
  // @@protoc_insertion_point(field_set:operations_research.IntervalVarAssignment.duration_min)
}

// optional int64 duration_max = 5;
inline void IntervalVarAssignment::clear_duration_max() {
  duration_max_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 IntervalVarAssignment::duration_max() const {
  // @@protoc_insertion_point(field_get:operations_research.IntervalVarAssignment.duration_max)
  return duration_max_;
}
inline void IntervalVarAssignment::set_duration_max(::google::protobuf::int64 value) {
  
  duration_max_ = value;
  // @@protoc_insertion_point(field_set:operations_research.IntervalVarAssignment.duration_max)
}

// optional int64 end_min = 6;
inline void IntervalVarAssignment::clear_end_min() {
  end_min_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 IntervalVarAssignment::end_min() const {
  // @@protoc_insertion_point(field_get:operations_research.IntervalVarAssignment.end_min)
  return end_min_;
}
inline void IntervalVarAssignment::set_end_min(::google::protobuf::int64 value) {
  
  end_min_ = value;
  // @@protoc_insertion_point(field_set:operations_research.IntervalVarAssignment.end_min)
}

// optional int64 end_max = 7;
inline void IntervalVarAssignment::clear_end_max() {
  end_max_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 IntervalVarAssignment::end_max() const {
  // @@protoc_insertion_point(field_get:operations_research.IntervalVarAssignment.end_max)
  return end_max_;
}
inline void IntervalVarAssignment::set_end_max(::google::protobuf::int64 value) {
  
  end_max_ = value;
  // @@protoc_insertion_point(field_set:operations_research.IntervalVarAssignment.end_max)
}

// optional int64 performed_min = 8;
inline void IntervalVarAssignment::clear_performed_min() {
  performed_min_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 IntervalVarAssignment::performed_min() const {
  // @@protoc_insertion_point(field_get:operations_research.IntervalVarAssignment.performed_min)
  return performed_min_;
}
inline void IntervalVarAssignment::set_performed_min(::google::protobuf::int64 value) {
  
  performed_min_ = value;
  // @@protoc_insertion_point(field_set:operations_research.IntervalVarAssignment.performed_min)
}

// optional int64 performed_max = 9;
inline void IntervalVarAssignment::clear_performed_max() {
  performed_max_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 IntervalVarAssignment::performed_max() const {
  // @@protoc_insertion_point(field_get:operations_research.IntervalVarAssignment.performed_max)
  return performed_max_;
}
inline void IntervalVarAssignment::set_performed_max(::google::protobuf::int64 value) {
  
  performed_max_ = value;
  // @@protoc_insertion_point(field_set:operations_research.IntervalVarAssignment.performed_max)
}

// optional bool active = 10;
inline void IntervalVarAssignment::clear_active() {
  active_ = false;
}
inline bool IntervalVarAssignment::active() const {
  // @@protoc_insertion_point(field_get:operations_research.IntervalVarAssignment.active)
  return active_;
}
inline void IntervalVarAssignment::set_active(bool value) {
  
  active_ = value;
  // @@protoc_insertion_point(field_set:operations_research.IntervalVarAssignment.active)
}

// -------------------------------------------------------------------

// SequenceVarAssignment

// optional string var_id = 1;
inline void SequenceVarAssignment::clear_var_id() {
  var_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SequenceVarAssignment::var_id() const {
  // @@protoc_insertion_point(field_get:operations_research.SequenceVarAssignment.var_id)
  return var_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SequenceVarAssignment::set_var_id(const ::std::string& value) {
  
  var_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:operations_research.SequenceVarAssignment.var_id)
}
inline void SequenceVarAssignment::set_var_id(const char* value) {
  
  var_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:operations_research.SequenceVarAssignment.var_id)
}
inline void SequenceVarAssignment::set_var_id(const char* value, size_t size) {
  
  var_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:operations_research.SequenceVarAssignment.var_id)
}
inline ::std::string* SequenceVarAssignment::mutable_var_id() {
  
  // @@protoc_insertion_point(field_mutable:operations_research.SequenceVarAssignment.var_id)
  return var_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SequenceVarAssignment::release_var_id() {
  // @@protoc_insertion_point(field_release:operations_research.SequenceVarAssignment.var_id)
  
  return var_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SequenceVarAssignment::set_allocated_var_id(::std::string* var_id) {
  if (var_id != NULL) {
    
  } else {
    
  }
  var_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), var_id);
  // @@protoc_insertion_point(field_set_allocated:operations_research.SequenceVarAssignment.var_id)
}

// repeated int32 forward_sequence = 2;
inline int SequenceVarAssignment::forward_sequence_size() const {
  return forward_sequence_.size();
}
inline void SequenceVarAssignment::clear_forward_sequence() {
  forward_sequence_.Clear();
}
inline ::google::protobuf::int32 SequenceVarAssignment::forward_sequence(int index) const {
  // @@protoc_insertion_point(field_get:operations_research.SequenceVarAssignment.forward_sequence)
  return forward_sequence_.Get(index);
}
inline void SequenceVarAssignment::set_forward_sequence(int index, ::google::protobuf::int32 value) {
  forward_sequence_.Set(index, value);
  // @@protoc_insertion_point(field_set:operations_research.SequenceVarAssignment.forward_sequence)
}
inline void SequenceVarAssignment::add_forward_sequence(::google::protobuf::int32 value) {
  forward_sequence_.Add(value);
  // @@protoc_insertion_point(field_add:operations_research.SequenceVarAssignment.forward_sequence)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
SequenceVarAssignment::forward_sequence() const {
  // @@protoc_insertion_point(field_list:operations_research.SequenceVarAssignment.forward_sequence)
  return forward_sequence_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
SequenceVarAssignment::mutable_forward_sequence() {
  // @@protoc_insertion_point(field_mutable_list:operations_research.SequenceVarAssignment.forward_sequence)
  return &forward_sequence_;
}

// repeated int32 backward_sequence = 3;
inline int SequenceVarAssignment::backward_sequence_size() const {
  return backward_sequence_.size();
}
inline void SequenceVarAssignment::clear_backward_sequence() {
  backward_sequence_.Clear();
}
inline ::google::protobuf::int32 SequenceVarAssignment::backward_sequence(int index) const {
  // @@protoc_insertion_point(field_get:operations_research.SequenceVarAssignment.backward_sequence)
  return backward_sequence_.Get(index);
}
inline void SequenceVarAssignment::set_backward_sequence(int index, ::google::protobuf::int32 value) {
  backward_sequence_.Set(index, value);
  // @@protoc_insertion_point(field_set:operations_research.SequenceVarAssignment.backward_sequence)
}
inline void SequenceVarAssignment::add_backward_sequence(::google::protobuf::int32 value) {
  backward_sequence_.Add(value);
  // @@protoc_insertion_point(field_add:operations_research.SequenceVarAssignment.backward_sequence)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
SequenceVarAssignment::backward_sequence() const {
  // @@protoc_insertion_point(field_list:operations_research.SequenceVarAssignment.backward_sequence)
  return backward_sequence_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
SequenceVarAssignment::mutable_backward_sequence() {
  // @@protoc_insertion_point(field_mutable_list:operations_research.SequenceVarAssignment.backward_sequence)
  return &backward_sequence_;
}

// repeated int32 unperformed = 4;
inline int SequenceVarAssignment::unperformed_size() const {
  return unperformed_.size();
}
inline void SequenceVarAssignment::clear_unperformed() {
  unperformed_.Clear();
}
inline ::google::protobuf::int32 SequenceVarAssignment::unperformed(int index) const {
  // @@protoc_insertion_point(field_get:operations_research.SequenceVarAssignment.unperformed)
  return unperformed_.Get(index);
}
inline void SequenceVarAssignment::set_unperformed(int index, ::google::protobuf::int32 value) {
  unperformed_.Set(index, value);
  // @@protoc_insertion_point(field_set:operations_research.SequenceVarAssignment.unperformed)
}
inline void SequenceVarAssignment::add_unperformed(::google::protobuf::int32 value) {
  unperformed_.Add(value);
  // @@protoc_insertion_point(field_add:operations_research.SequenceVarAssignment.unperformed)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
SequenceVarAssignment::unperformed() const {
  // @@protoc_insertion_point(field_list:operations_research.SequenceVarAssignment.unperformed)
  return unperformed_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
SequenceVarAssignment::mutable_unperformed() {
  // @@protoc_insertion_point(field_mutable_list:operations_research.SequenceVarAssignment.unperformed)
  return &unperformed_;
}

// optional bool active = 5;
inline void SequenceVarAssignment::clear_active() {
  active_ = false;
}
inline bool SequenceVarAssignment::active() const {
  // @@protoc_insertion_point(field_get:operations_research.SequenceVarAssignment.active)
  return active_;
}
inline void SequenceVarAssignment::set_active(bool value) {
  
  active_ = value;
  // @@protoc_insertion_point(field_set:operations_research.SequenceVarAssignment.active)
}

// -------------------------------------------------------------------

// WorkerInfo

// optional int32 worker_id = 1;
inline void WorkerInfo::clear_worker_id() {
  worker_id_ = 0;
}
inline ::google::protobuf::int32 WorkerInfo::worker_id() const {
  // @@protoc_insertion_point(field_get:operations_research.WorkerInfo.worker_id)
  return worker_id_;
}
inline void WorkerInfo::set_worker_id(::google::protobuf::int32 value) {
  
  worker_id_ = value;
  // @@protoc_insertion_point(field_set:operations_research.WorkerInfo.worker_id)
}

// optional string bns = 2;
inline void WorkerInfo::clear_bns() {
  bns_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& WorkerInfo::bns() const {
  // @@protoc_insertion_point(field_get:operations_research.WorkerInfo.bns)
  return bns_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void WorkerInfo::set_bns(const ::std::string& value) {
  
  bns_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:operations_research.WorkerInfo.bns)
}
inline void WorkerInfo::set_bns(const char* value) {
  
  bns_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:operations_research.WorkerInfo.bns)
}
inline void WorkerInfo::set_bns(const char* value, size_t size) {
  
  bns_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:operations_research.WorkerInfo.bns)
}
inline ::std::string* WorkerInfo::mutable_bns() {
  
  // @@protoc_insertion_point(field_mutable:operations_research.WorkerInfo.bns)
  return bns_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* WorkerInfo::release_bns() {
  // @@protoc_insertion_point(field_release:operations_research.WorkerInfo.bns)
  
  return bns_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void WorkerInfo::set_allocated_bns(::std::string* bns) {
  if (bns != NULL) {
    
  } else {
    
  }
  bns_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), bns);
  // @@protoc_insertion_point(field_set_allocated:operations_research.WorkerInfo.bns)
}

// -------------------------------------------------------------------

// AssignmentProto

// repeated .operations_research.IntVarAssignment int_var_assignment = 1;
inline int AssignmentProto::int_var_assignment_size() const {
  return int_var_assignment_.size();
}
inline void AssignmentProto::clear_int_var_assignment() {
  int_var_assignment_.Clear();
}
inline const ::operations_research::IntVarAssignment& AssignmentProto::int_var_assignment(int index) const {
  // @@protoc_insertion_point(field_get:operations_research.AssignmentProto.int_var_assignment)
  return int_var_assignment_.Get(index);
}
inline ::operations_research::IntVarAssignment* AssignmentProto::mutable_int_var_assignment(int index) {
  // @@protoc_insertion_point(field_mutable:operations_research.AssignmentProto.int_var_assignment)
  return int_var_assignment_.Mutable(index);
}
inline ::operations_research::IntVarAssignment* AssignmentProto::add_int_var_assignment() {
  // @@protoc_insertion_point(field_add:operations_research.AssignmentProto.int_var_assignment)
  return int_var_assignment_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::operations_research::IntVarAssignment >*
AssignmentProto::mutable_int_var_assignment() {
  // @@protoc_insertion_point(field_mutable_list:operations_research.AssignmentProto.int_var_assignment)
  return &int_var_assignment_;
}
inline const ::google::protobuf::RepeatedPtrField< ::operations_research::IntVarAssignment >&
AssignmentProto::int_var_assignment() const {
  // @@protoc_insertion_point(field_list:operations_research.AssignmentProto.int_var_assignment)
  return int_var_assignment_;
}

// repeated .operations_research.IntervalVarAssignment interval_var_assignment = 2;
inline int AssignmentProto::interval_var_assignment_size() const {
  return interval_var_assignment_.size();
}
inline void AssignmentProto::clear_interval_var_assignment() {
  interval_var_assignment_.Clear();
}
inline const ::operations_research::IntervalVarAssignment& AssignmentProto::interval_var_assignment(int index) const {
  // @@protoc_insertion_point(field_get:operations_research.AssignmentProto.interval_var_assignment)
  return interval_var_assignment_.Get(index);
}
inline ::operations_research::IntervalVarAssignment* AssignmentProto::mutable_interval_var_assignment(int index) {
  // @@protoc_insertion_point(field_mutable:operations_research.AssignmentProto.interval_var_assignment)
  return interval_var_assignment_.Mutable(index);
}
inline ::operations_research::IntervalVarAssignment* AssignmentProto::add_interval_var_assignment() {
  // @@protoc_insertion_point(field_add:operations_research.AssignmentProto.interval_var_assignment)
  return interval_var_assignment_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::operations_research::IntervalVarAssignment >*
AssignmentProto::mutable_interval_var_assignment() {
  // @@protoc_insertion_point(field_mutable_list:operations_research.AssignmentProto.interval_var_assignment)
  return &interval_var_assignment_;
}
inline const ::google::protobuf::RepeatedPtrField< ::operations_research::IntervalVarAssignment >&
AssignmentProto::interval_var_assignment() const {
  // @@protoc_insertion_point(field_list:operations_research.AssignmentProto.interval_var_assignment)
  return interval_var_assignment_;
}

// repeated .operations_research.SequenceVarAssignment sequence_var_assignment = 6;
inline int AssignmentProto::sequence_var_assignment_size() const {
  return sequence_var_assignment_.size();
}
inline void AssignmentProto::clear_sequence_var_assignment() {
  sequence_var_assignment_.Clear();
}
inline const ::operations_research::SequenceVarAssignment& AssignmentProto::sequence_var_assignment(int index) const {
  // @@protoc_insertion_point(field_get:operations_research.AssignmentProto.sequence_var_assignment)
  return sequence_var_assignment_.Get(index);
}
inline ::operations_research::SequenceVarAssignment* AssignmentProto::mutable_sequence_var_assignment(int index) {
  // @@protoc_insertion_point(field_mutable:operations_research.AssignmentProto.sequence_var_assignment)
  return sequence_var_assignment_.Mutable(index);
}
inline ::operations_research::SequenceVarAssignment* AssignmentProto::add_sequence_var_assignment() {
  // @@protoc_insertion_point(field_add:operations_research.AssignmentProto.sequence_var_assignment)
  return sequence_var_assignment_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::operations_research::SequenceVarAssignment >*
AssignmentProto::mutable_sequence_var_assignment() {
  // @@protoc_insertion_point(field_mutable_list:operations_research.AssignmentProto.sequence_var_assignment)
  return &sequence_var_assignment_;
}
inline const ::google::protobuf::RepeatedPtrField< ::operations_research::SequenceVarAssignment >&
AssignmentProto::sequence_var_assignment() const {
  // @@protoc_insertion_point(field_list:operations_research.AssignmentProto.sequence_var_assignment)
  return sequence_var_assignment_;
}

// optional .operations_research.IntVarAssignment objective = 3;
inline bool AssignmentProto::has_objective() const {
  return !_is_default_instance_ && objective_ != NULL;
}
inline void AssignmentProto::clear_objective() {
  if (GetArenaNoVirtual() == NULL && objective_ != NULL) delete objective_;
  objective_ = NULL;
}
inline const ::operations_research::IntVarAssignment& AssignmentProto::objective() const {
  // @@protoc_insertion_point(field_get:operations_research.AssignmentProto.objective)
  return objective_ != NULL ? *objective_ : *default_instance_->objective_;
}
inline ::operations_research::IntVarAssignment* AssignmentProto::mutable_objective() {
  
  if (objective_ == NULL) {
    objective_ = new ::operations_research::IntVarAssignment;
  }
  // @@protoc_insertion_point(field_mutable:operations_research.AssignmentProto.objective)
  return objective_;
}
inline ::operations_research::IntVarAssignment* AssignmentProto::release_objective() {
  // @@protoc_insertion_point(field_release:operations_research.AssignmentProto.objective)
  
  ::operations_research::IntVarAssignment* temp = objective_;
  objective_ = NULL;
  return temp;
}
inline void AssignmentProto::set_allocated_objective(::operations_research::IntVarAssignment* objective) {
  delete objective_;
  objective_ = objective;
  if (objective) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:operations_research.AssignmentProto.objective)
}

// optional .operations_research.WorkerInfo worker_info = 4;
inline bool AssignmentProto::has_worker_info() const {
  return !_is_default_instance_ && worker_info_ != NULL;
}
inline void AssignmentProto::clear_worker_info() {
  if (GetArenaNoVirtual() == NULL && worker_info_ != NULL) delete worker_info_;
  worker_info_ = NULL;
}
inline const ::operations_research::WorkerInfo& AssignmentProto::worker_info() const {
  // @@protoc_insertion_point(field_get:operations_research.AssignmentProto.worker_info)
  return worker_info_ != NULL ? *worker_info_ : *default_instance_->worker_info_;
}
inline ::operations_research::WorkerInfo* AssignmentProto::mutable_worker_info() {
  
  if (worker_info_ == NULL) {
    worker_info_ = new ::operations_research::WorkerInfo;
  }
  // @@protoc_insertion_point(field_mutable:operations_research.AssignmentProto.worker_info)
  return worker_info_;
}
inline ::operations_research::WorkerInfo* AssignmentProto::release_worker_info() {
  // @@protoc_insertion_point(field_release:operations_research.AssignmentProto.worker_info)
  
  ::operations_research::WorkerInfo* temp = worker_info_;
  worker_info_ = NULL;
  return temp;
}
inline void AssignmentProto::set_allocated_worker_info(::operations_research::WorkerInfo* worker_info) {
  delete worker_info_;
  worker_info_ = worker_info;
  if (worker_info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:operations_research.AssignmentProto.worker_info)
}

// optional bool is_valid = 5;
inline void AssignmentProto::clear_is_valid() {
  is_valid_ = false;
}
inline bool AssignmentProto::is_valid() const {
  // @@protoc_insertion_point(field_get:operations_research.AssignmentProto.is_valid)
  return is_valid_;
}
inline void AssignmentProto::set_is_valid(bool value) {
  
  is_valid_ = value;
  // @@protoc_insertion_point(field_set:operations_research.AssignmentProto.is_valid)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace operations_research

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_constraint_5fsolver_2fassignment_2eproto__INCLUDED
