// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: graph/flow_problem.proto

#ifndef PROTOBUF_graph_2fflow_5fproblem_2eproto__INCLUDED
#define PROTOBUF_graph_2fflow_5fproblem_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace operations_research {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_graph_2fflow_5fproblem_2eproto();
void protobuf_AssignDesc_graph_2fflow_5fproblem_2eproto();
void protobuf_ShutdownFile_graph_2fflow_5fproblem_2eproto();

class Arc;
class FlowModel;
class Node;

enum FlowModel_ProblemType {
  FlowModel_ProblemType_LINEAR_SUM_ASSIGNMENT = 0,
  FlowModel_ProblemType_MAX_FLOW = 1,
  FlowModel_ProblemType_MIN_COST_FLOW = 2
};
bool FlowModel_ProblemType_IsValid(int value);
const FlowModel_ProblemType FlowModel_ProblemType_ProblemType_MIN = FlowModel_ProblemType_LINEAR_SUM_ASSIGNMENT;
const FlowModel_ProblemType FlowModel_ProblemType_ProblemType_MAX = FlowModel_ProblemType_MIN_COST_FLOW;
const int FlowModel_ProblemType_ProblemType_ARRAYSIZE = FlowModel_ProblemType_ProblemType_MAX + 1;

const ::google::protobuf::EnumDescriptor* FlowModel_ProblemType_descriptor();
inline const ::std::string& FlowModel_ProblemType_Name(FlowModel_ProblemType value) {
  return ::google::protobuf::internal::NameOfEnum(
    FlowModel_ProblemType_descriptor(), value);
}
inline bool FlowModel_ProblemType_Parse(
    const ::std::string& name, FlowModel_ProblemType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<FlowModel_ProblemType>(
    FlowModel_ProblemType_descriptor(), name, value);
}
// ===================================================================

class Arc : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:operations_research.Arc) */ {
 public:
  Arc();
  virtual ~Arc();

  Arc(const Arc& from);

  inline Arc& operator=(const Arc& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Arc& default_instance();

  void Swap(Arc* other);

  // implements Message ----------------------------------------------

  inline Arc* New() const { return New(NULL); }

  Arc* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Arc& from);
  void MergeFrom(const Arc& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Arc* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 tail_node_id = 1;
  bool has_tail_node_id() const;
  void clear_tail_node_id();
  static const int kTailNodeIdFieldNumber = 1;
  ::google::protobuf::int64 tail_node_id() const;
  void set_tail_node_id(::google::protobuf::int64 value);

  // optional int64 head_node_id = 2;
  bool has_head_node_id() const;
  void clear_head_node_id();
  static const int kHeadNodeIdFieldNumber = 2;
  ::google::protobuf::int64 head_node_id() const;
  void set_head_node_id(::google::protobuf::int64 value);

  // optional int64 capacity = 3 [default = 1];
  bool has_capacity() const;
  void clear_capacity();
  static const int kCapacityFieldNumber = 3;
  ::google::protobuf::int64 capacity() const;
  void set_capacity(::google::protobuf::int64 value);

  // optional int64 unit_cost = 4 [default = 0];
  bool has_unit_cost() const;
  void clear_unit_cost();
  static const int kUnitCostFieldNumber = 4;
  ::google::protobuf::int64 unit_cost() const;
  void set_unit_cost(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:operations_research.Arc)
 private:
  inline void set_has_tail_node_id();
  inline void clear_has_tail_node_id();
  inline void set_has_head_node_id();
  inline void clear_has_head_node_id();
  inline void set_has_capacity();
  inline void clear_has_capacity();
  inline void set_has_unit_cost();
  inline void clear_has_unit_cost();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 tail_node_id_;
  ::google::protobuf::int64 head_node_id_;
  ::google::protobuf::int64 capacity_;
  ::google::protobuf::int64 unit_cost_;
  friend void  protobuf_AddDesc_graph_2fflow_5fproblem_2eproto();
  friend void protobuf_AssignDesc_graph_2fflow_5fproblem_2eproto();
  friend void protobuf_ShutdownFile_graph_2fflow_5fproblem_2eproto();

  void InitAsDefaultInstance();
  static Arc* default_instance_;
};
// -------------------------------------------------------------------

class Node : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:operations_research.Node) */ {
 public:
  Node();
  virtual ~Node();

  Node(const Node& from);

  inline Node& operator=(const Node& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Node& default_instance();

  void Swap(Node* other);

  // implements Message ----------------------------------------------

  inline Node* New() const { return New(NULL); }

  Node* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Node& from);
  void MergeFrom(const Node& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Node* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int64 id() const;
  void set_id(::google::protobuf::int64 value);

  // optional int64 supply = 2 [default = 0];
  bool has_supply() const;
  void clear_supply();
  static const int kSupplyFieldNumber = 2;
  ::google::protobuf::int64 supply() const;
  void set_supply(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:operations_research.Node)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_supply();
  inline void clear_has_supply();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 id_;
  ::google::protobuf::int64 supply_;
  friend void  protobuf_AddDesc_graph_2fflow_5fproblem_2eproto();
  friend void protobuf_AssignDesc_graph_2fflow_5fproblem_2eproto();
  friend void protobuf_ShutdownFile_graph_2fflow_5fproblem_2eproto();

  void InitAsDefaultInstance();
  static Node* default_instance_;
};
// -------------------------------------------------------------------

class FlowModel : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:operations_research.FlowModel) */ {
 public:
  FlowModel();
  virtual ~FlowModel();

  FlowModel(const FlowModel& from);

  inline FlowModel& operator=(const FlowModel& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FlowModel& default_instance();

  void Swap(FlowModel* other);

  // implements Message ----------------------------------------------

  inline FlowModel* New() const { return New(NULL); }

  FlowModel* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FlowModel& from);
  void MergeFrom(const FlowModel& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(FlowModel* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef FlowModel_ProblemType ProblemType;
  static const ProblemType LINEAR_SUM_ASSIGNMENT =
    FlowModel_ProblemType_LINEAR_SUM_ASSIGNMENT;
  static const ProblemType MAX_FLOW =
    FlowModel_ProblemType_MAX_FLOW;
  static const ProblemType MIN_COST_FLOW =
    FlowModel_ProblemType_MIN_COST_FLOW;
  static inline bool ProblemType_IsValid(int value) {
    return FlowModel_ProblemType_IsValid(value);
  }
  static const ProblemType ProblemType_MIN =
    FlowModel_ProblemType_ProblemType_MIN;
  static const ProblemType ProblemType_MAX =
    FlowModel_ProblemType_ProblemType_MAX;
  static const int ProblemType_ARRAYSIZE =
    FlowModel_ProblemType_ProblemType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ProblemType_descriptor() {
    return FlowModel_ProblemType_descriptor();
  }
  static inline const ::std::string& ProblemType_Name(ProblemType value) {
    return FlowModel_ProblemType_Name(value);
  }
  static inline bool ProblemType_Parse(const ::std::string& name,
      ProblemType* value) {
    return FlowModel_ProblemType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated .operations_research.Node node = 1;
  int node_size() const;
  void clear_node();
  static const int kNodeFieldNumber = 1;
  const ::operations_research::Node& node(int index) const;
  ::operations_research::Node* mutable_node(int index);
  ::operations_research::Node* add_node();
  ::google::protobuf::RepeatedPtrField< ::operations_research::Node >*
      mutable_node();
  const ::google::protobuf::RepeatedPtrField< ::operations_research::Node >&
      node() const;

  // repeated .operations_research.Arc arc = 2;
  int arc_size() const;
  void clear_arc();
  static const int kArcFieldNumber = 2;
  const ::operations_research::Arc& arc(int index) const;
  ::operations_research::Arc* mutable_arc(int index);
  ::operations_research::Arc* add_arc();
  ::google::protobuf::RepeatedPtrField< ::operations_research::Arc >*
      mutable_arc();
  const ::google::protobuf::RepeatedPtrField< ::operations_research::Arc >&
      arc() const;

  // optional .operations_research.FlowModel.ProblemType problem_type = 3 [default = MIN_COST_FLOW];
  bool has_problem_type() const;
  void clear_problem_type();
  static const int kProblemTypeFieldNumber = 3;
  ::operations_research::FlowModel_ProblemType problem_type() const;
  void set_problem_type(::operations_research::FlowModel_ProblemType value);

  // @@protoc_insertion_point(class_scope:operations_research.FlowModel)
 private:
  inline void set_has_problem_type();
  inline void clear_has_problem_type();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::operations_research::Node > node_;
  ::google::protobuf::RepeatedPtrField< ::operations_research::Arc > arc_;
  int problem_type_;
  friend void  protobuf_AddDesc_graph_2fflow_5fproblem_2eproto();
  friend void protobuf_AssignDesc_graph_2fflow_5fproblem_2eproto();
  friend void protobuf_ShutdownFile_graph_2fflow_5fproblem_2eproto();

  void InitAsDefaultInstance();
  static FlowModel* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Arc

// optional int64 tail_node_id = 1;
inline bool Arc::has_tail_node_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Arc::set_has_tail_node_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Arc::clear_has_tail_node_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Arc::clear_tail_node_id() {
  tail_node_id_ = GOOGLE_LONGLONG(0);
  clear_has_tail_node_id();
}
inline ::google::protobuf::int64 Arc::tail_node_id() const {
  // @@protoc_insertion_point(field_get:operations_research.Arc.tail_node_id)
  return tail_node_id_;
}
inline void Arc::set_tail_node_id(::google::protobuf::int64 value) {
  set_has_tail_node_id();
  tail_node_id_ = value;
  // @@protoc_insertion_point(field_set:operations_research.Arc.tail_node_id)
}

// optional int64 head_node_id = 2;
inline bool Arc::has_head_node_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Arc::set_has_head_node_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Arc::clear_has_head_node_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Arc::clear_head_node_id() {
  head_node_id_ = GOOGLE_LONGLONG(0);
  clear_has_head_node_id();
}
inline ::google::protobuf::int64 Arc::head_node_id() const {
  // @@protoc_insertion_point(field_get:operations_research.Arc.head_node_id)
  return head_node_id_;
}
inline void Arc::set_head_node_id(::google::protobuf::int64 value) {
  set_has_head_node_id();
  head_node_id_ = value;
  // @@protoc_insertion_point(field_set:operations_research.Arc.head_node_id)
}

// optional int64 capacity = 3 [default = 1];
inline bool Arc::has_capacity() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Arc::set_has_capacity() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Arc::clear_has_capacity() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Arc::clear_capacity() {
  capacity_ = GOOGLE_LONGLONG(1);
  clear_has_capacity();
}
inline ::google::protobuf::int64 Arc::capacity() const {
  // @@protoc_insertion_point(field_get:operations_research.Arc.capacity)
  return capacity_;
}
inline void Arc::set_capacity(::google::protobuf::int64 value) {
  set_has_capacity();
  capacity_ = value;
  // @@protoc_insertion_point(field_set:operations_research.Arc.capacity)
}

// optional int64 unit_cost = 4 [default = 0];
inline bool Arc::has_unit_cost() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Arc::set_has_unit_cost() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Arc::clear_has_unit_cost() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Arc::clear_unit_cost() {
  unit_cost_ = GOOGLE_LONGLONG(0);
  clear_has_unit_cost();
}
inline ::google::protobuf::int64 Arc::unit_cost() const {
  // @@protoc_insertion_point(field_get:operations_research.Arc.unit_cost)
  return unit_cost_;
}
inline void Arc::set_unit_cost(::google::protobuf::int64 value) {
  set_has_unit_cost();
  unit_cost_ = value;
  // @@protoc_insertion_point(field_set:operations_research.Arc.unit_cost)
}

// -------------------------------------------------------------------

// Node

// optional int64 id = 1;
inline bool Node::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Node::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Node::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Node::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::int64 Node::id() const {
  // @@protoc_insertion_point(field_get:operations_research.Node.id)
  return id_;
}
inline void Node::set_id(::google::protobuf::int64 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:operations_research.Node.id)
}

// optional int64 supply = 2 [default = 0];
inline bool Node::has_supply() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Node::set_has_supply() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Node::clear_has_supply() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Node::clear_supply() {
  supply_ = GOOGLE_LONGLONG(0);
  clear_has_supply();
}
inline ::google::protobuf::int64 Node::supply() const {
  // @@protoc_insertion_point(field_get:operations_research.Node.supply)
  return supply_;
}
inline void Node::set_supply(::google::protobuf::int64 value) {
  set_has_supply();
  supply_ = value;
  // @@protoc_insertion_point(field_set:operations_research.Node.supply)
}

// -------------------------------------------------------------------

// FlowModel

// repeated .operations_research.Node node = 1;
inline int FlowModel::node_size() const {
  return node_.size();
}
inline void FlowModel::clear_node() {
  node_.Clear();
}
inline const ::operations_research::Node& FlowModel::node(int index) const {
  // @@protoc_insertion_point(field_get:operations_research.FlowModel.node)
  return node_.Get(index);
}
inline ::operations_research::Node* FlowModel::mutable_node(int index) {
  // @@protoc_insertion_point(field_mutable:operations_research.FlowModel.node)
  return node_.Mutable(index);
}
inline ::operations_research::Node* FlowModel::add_node() {
  // @@protoc_insertion_point(field_add:operations_research.FlowModel.node)
  return node_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::operations_research::Node >*
FlowModel::mutable_node() {
  // @@protoc_insertion_point(field_mutable_list:operations_research.FlowModel.node)
  return &node_;
}
inline const ::google::protobuf::RepeatedPtrField< ::operations_research::Node >&
FlowModel::node() const {
  // @@protoc_insertion_point(field_list:operations_research.FlowModel.node)
  return node_;
}

// repeated .operations_research.Arc arc = 2;
inline int FlowModel::arc_size() const {
  return arc_.size();
}
inline void FlowModel::clear_arc() {
  arc_.Clear();
}
inline const ::operations_research::Arc& FlowModel::arc(int index) const {
  // @@protoc_insertion_point(field_get:operations_research.FlowModel.arc)
  return arc_.Get(index);
}
inline ::operations_research::Arc* FlowModel::mutable_arc(int index) {
  // @@protoc_insertion_point(field_mutable:operations_research.FlowModel.arc)
  return arc_.Mutable(index);
}
inline ::operations_research::Arc* FlowModel::add_arc() {
  // @@protoc_insertion_point(field_add:operations_research.FlowModel.arc)
  return arc_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::operations_research::Arc >*
FlowModel::mutable_arc() {
  // @@protoc_insertion_point(field_mutable_list:operations_research.FlowModel.arc)
  return &arc_;
}
inline const ::google::protobuf::RepeatedPtrField< ::operations_research::Arc >&
FlowModel::arc() const {
  // @@protoc_insertion_point(field_list:operations_research.FlowModel.arc)
  return arc_;
}

// optional .operations_research.FlowModel.ProblemType problem_type = 3 [default = MIN_COST_FLOW];
inline bool FlowModel::has_problem_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void FlowModel::set_has_problem_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void FlowModel::clear_has_problem_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void FlowModel::clear_problem_type() {
  problem_type_ = 2;
  clear_has_problem_type();
}
inline ::operations_research::FlowModel_ProblemType FlowModel::problem_type() const {
  // @@protoc_insertion_point(field_get:operations_research.FlowModel.problem_type)
  return static_cast< ::operations_research::FlowModel_ProblemType >(problem_type_);
}
inline void FlowModel::set_problem_type(::operations_research::FlowModel_ProblemType value) {
  assert(::operations_research::FlowModel_ProblemType_IsValid(value));
  set_has_problem_type();
  problem_type_ = value;
  // @@protoc_insertion_point(field_set:operations_research.FlowModel.problem_type)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace operations_research

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::operations_research::FlowModel_ProblemType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::operations_research::FlowModel_ProblemType>() {
  return ::operations_research::FlowModel_ProblemType_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_graph_2fflow_5fproblem_2eproto__INCLUDED
